import { Config } from "../../../config";
import { API_ENDPOINTS } from "../../../constants/apiEndpoints";
import {
  BluefinXTx,
  SponsorRequest,
  SponsorResponse,
  SwapResponse,
} from "./types";

const request = async <T = any>(path: string, body: any) => {
  const headers = new Headers({
    "Content-Type": "application/json",
  });
  const bluefinXApiKey = (Config.getBluefinXApiKey() || "").trim();
  if (bluefinXApiKey) {
    headers.set("Bluefin-X-API-Key", bluefinXApiKey);
  }
  const res = await fetch(`${Config.getApi() || API_ENDPOINTS.MAIN}/${path}`, {
    method: "POST",
    body: JSON.stringify(body),
    headers,
  });
  return res.json() as T;
};
export const sponsorBluefinX = async (body: SponsorRequest) => {
  return await request<SponsorResponse>("bluefinx/sponsor", body);
};

/**
 * Request BluefinX for signing sponsored tx and execute it
 *
 * @Warning
 * User must use this function to execute BluefinX tx, otherwise the tx will be rejected by BluefinX contract
 * @param tx - BluefinX tx which is generated by `buildTx`
 * @param signature - user signature after signing the transaction
 * @returns `SwapResponse`
 */
export const executeBluefinTx = async (tx: BluefinXTx, signature: string) => {
  return await request<SwapResponse>("bluefinx/swap", {
    quoteId: tx.quoteId,
    txBytes: tx.txBytes,
    signature,
  });
};
